// Code generated by protoc-gen-go.
// source: thing.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	thing.proto

It has these top-level messages:
	ThingIDArray
	Thing
	ThingIDRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ThingIDArray struct {
	Things []int32 `protobuf:"varint,1,rep,packed,name=things" json:"things,omitempty"`
}

func (m *ThingIDArray) Reset()                    { *m = ThingIDArray{} }
func (m *ThingIDArray) String() string            { return proto1.CompactTextString(m) }
func (*ThingIDArray) ProtoMessage()               {}
func (*ThingIDArray) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ThingIDArray) GetThings() []int32 {
	if m != nil {
		return m.Things
	}
	return nil
}

type Thing struct {
	ID          int32                      `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string                     `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	CreatedAt   *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt   *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Thing) Reset()                    { *m = Thing{} }
func (m *Thing) String() string            { return proto1.CompactTextString(m) }
func (*Thing) ProtoMessage()               {}
func (*Thing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Thing) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Thing) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Thing) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Thing) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ThingIDRequest struct {
	ID int32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *ThingIDRequest) Reset()                    { *m = ThingIDRequest{} }
func (m *ThingIDRequest) String() string            { return proto1.CompactTextString(m) }
func (*ThingIDRequest) ProtoMessage()               {}
func (*ThingIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ThingIDRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto1.RegisterType((*ThingIDArray)(nil), "proto.ThingIDArray")
	proto1.RegisterType((*Thing)(nil), "proto.Thing")
	proto1.RegisterType((*ThingIDRequest)(nil), "proto.ThingIDRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ThingSvc service

type ThingSvcClient interface {
	GetThing(ctx context.Context, in *ThingIDRequest, opts ...grpc.CallOption) (*Thing, error)
	CreateThing(ctx context.Context, in *Thing, opts ...grpc.CallOption) (*Thing, error)
	UpdateThing(ctx context.Context, in *Thing, opts ...grpc.CallOption) (*Thing, error)
	DeleteThing(ctx context.Context, in *ThingIDRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	BulkDeleteThing(ctx context.Context, in *ThingIDArray, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type thingSvcClient struct {
	cc *grpc.ClientConn
}

func NewThingSvcClient(cc *grpc.ClientConn) ThingSvcClient {
	return &thingSvcClient{cc}
}

func (c *thingSvcClient) GetThing(ctx context.Context, in *ThingIDRequest, opts ...grpc.CallOption) (*Thing, error) {
	out := new(Thing)
	err := grpc.Invoke(ctx, "/proto.ThingSvc/GetThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingSvcClient) CreateThing(ctx context.Context, in *Thing, opts ...grpc.CallOption) (*Thing, error) {
	out := new(Thing)
	err := grpc.Invoke(ctx, "/proto.ThingSvc/CreateThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingSvcClient) UpdateThing(ctx context.Context, in *Thing, opts ...grpc.CallOption) (*Thing, error) {
	out := new(Thing)
	err := grpc.Invoke(ctx, "/proto.ThingSvc/UpdateThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingSvcClient) DeleteThing(ctx context.Context, in *ThingIDRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.ThingSvc/DeleteThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingSvcClient) BulkDeleteThing(ctx context.Context, in *ThingIDArray, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.ThingSvc/BulkDeleteThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ThingSvc service

type ThingSvcServer interface {
	GetThing(context.Context, *ThingIDRequest) (*Thing, error)
	CreateThing(context.Context, *Thing) (*Thing, error)
	UpdateThing(context.Context, *Thing) (*Thing, error)
	DeleteThing(context.Context, *ThingIDRequest) (*google_protobuf1.Empty, error)
	BulkDeleteThing(context.Context, *ThingIDArray) (*google_protobuf1.Empty, error)
}

func RegisterThingSvcServer(s *grpc.Server, srv ThingSvcServer) {
	s.RegisterService(&_ThingSvc_serviceDesc, srv)
}

func _ThingSvc_GetThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThingIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingSvcServer).GetThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ThingSvc/GetThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingSvcServer).GetThing(ctx, req.(*ThingIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThingSvc_CreateThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Thing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingSvcServer).CreateThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ThingSvc/CreateThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingSvcServer).CreateThing(ctx, req.(*Thing))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThingSvc_UpdateThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Thing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingSvcServer).UpdateThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ThingSvc/UpdateThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingSvcServer).UpdateThing(ctx, req.(*Thing))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThingSvc_DeleteThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThingIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingSvcServer).DeleteThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ThingSvc/DeleteThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingSvcServer).DeleteThing(ctx, req.(*ThingIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThingSvc_BulkDeleteThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThingIDArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingSvcServer).BulkDeleteThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ThingSvc/BulkDeleteThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingSvcServer).BulkDeleteThing(ctx, req.(*ThingIDArray))
	}
	return interceptor(ctx, in, info, handler)
}

var _ThingSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ThingSvc",
	HandlerType: (*ThingSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThing",
			Handler:    _ThingSvc_GetThing_Handler,
		},
		{
			MethodName: "CreateThing",
			Handler:    _ThingSvc_CreateThing_Handler,
		},
		{
			MethodName: "UpdateThing",
			Handler:    _ThingSvc_UpdateThing_Handler,
		},
		{
			MethodName: "DeleteThing",
			Handler:    _ThingSvc_DeleteThing_Handler,
		},
		{
			MethodName: "BulkDeleteThing",
			Handler:    _ThingSvc_BulkDeleteThing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thing.proto",
}

func init() { proto1.RegisterFile("thing.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0xb3, 0x40,
	0x14, 0x85, 0x3b, 0xb4, 0x34, 0xed, 0xa5, 0xe9, 0x9f, 0xcc, 0x1f, 0x1b, 0x82, 0x0b, 0x27, 0x2c,
	0x0c, 0x89, 0x09, 0x8d, 0x75, 0xe5, 0xc6, 0x58, 0xc5, 0x98, 0x6e, 0xb1, 0xae, 0x0d, 0x6d, 0xaf,
	0x95, 0x58, 0x0a, 0xc2, 0xc5, 0xa4, 0x8f, 0xe2, 0xf3, 0xf8, 0x62, 0x86, 0x19, 0x48, 0xa0, 0xda,
	0xe8, 0x0a, 0xe6, 0xde, 0xef, 0x1c, 0xce, 0x01, 0xc0, 0xa0, 0x97, 0x70, 0xbb, 0x76, 0x93, 0x34,
	0xa6, 0x98, 0xeb, 0xf2, 0x62, 0x9d, 0xac, 0xe3, 0x78, 0xbd, 0xc1, 0xb1, 0x3c, 0x2d, 0xf2, 0xe7,
	0x31, 0x85, 0x11, 0x66, 0x14, 0x44, 0x89, 0xe2, 0xac, 0xe3, 0x7d, 0x00, 0xa3, 0x84, 0x76, 0x6a,
	0x69, 0x9f, 0xc2, 0x60, 0x5e, 0x78, 0xce, 0xbc, 0x69, 0x9a, 0x06, 0x3b, 0x3e, 0x82, 0xae, 0x7c,
	0x46, 0x66, 0x32, 0xd1, 0x76, 0x74, 0xbf, 0x3c, 0xd9, 0x9f, 0x0c, 0x74, 0x09, 0xf2, 0x21, 0x68,
	0x33, 0xcf, 0x64, 0x82, 0x39, 0xba, 0xaf, 0xcd, 0x3c, 0xce, 0xa1, 0xb3, 0x0d, 0x22, 0x34, 0x35,
	0xc1, 0x9c, 0xbe, 0x2f, 0xef, 0xb9, 0x00, 0x63, 0x85, 0xd9, 0x32, 0x0d, 0x13, 0x0a, 0xe3, 0xad,
	0xd9, 0x96, 0xab, 0xfa, 0x88, 0x5f, 0x02, 0x2c, 0x53, 0x0c, 0x08, 0x57, 0x4f, 0x01, 0x99, 0x1d,
	0xc1, 0x1c, 0x63, 0x62, 0xb9, 0x2a, 0xa9, 0x5b, 0x25, 0x75, 0xe7, 0x55, 0x15, 0xbf, 0x5f, 0xd2,
	0x53, 0x2a, 0xa4, 0x79, 0xb2, 0xaa, 0xa4, 0xfa, 0xef, 0xd2, 0x92, 0x9e, 0x92, 0x2d, 0x60, 0x58,
	0xb6, 0xf5, 0xf1, 0x2d, 0xc7, 0x8c, 0xf6, 0xdb, 0x4c, 0x3e, 0x34, 0xe8, 0x49, 0xe4, 0xe1, 0x7d,
	0xc9, 0xcf, 0xa1, 0x77, 0x8f, 0xa4, 0x6a, 0x1f, 0x29, 0x6b, 0xb7, 0xa9, 0xb7, 0x06, 0xf5, 0xb1,
	0xdd, 0xe2, 0x67, 0x60, 0xdc, 0xca, 0xa4, 0x4a, 0xd5, 0x58, 0xff, 0x04, 0x3f, 0xca, 0x6c, 0x7f,
	0x81, 0xaf, 0xc0, 0xf0, 0x70, 0x83, 0x15, 0x7c, 0x20, 0xcf, 0xe8, 0xdb, 0x8b, 0xb8, 0x2b, 0xbe,
	0xb6, 0xdd, 0xe2, 0xd7, 0xf0, 0xef, 0x26, 0xdf, 0xbc, 0xd6, 0x3d, 0xfe, 0x37, 0x3d, 0xe4, 0x1f,
	0x70, 0xd8, 0x61, 0xd1, 0x95, 0x93, 0x8b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x8a, 0x24,
	0x67, 0x86, 0x02, 0x00, 0x00,
}
